version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: profitplus-erp-mock
    environment:
      SA_PASSWORD: "YourStr0ngP@ssw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_COLLATION: "Modern_Spanish_CI_AS"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
      - ./mssql/Ncake_a.bak:/var/opt/mssql/backup/Ncake_a.bak
    networks:
      - profitplus-network

volumes:
  mssql-data:

networks:
  profitplus-network:
    driver: bridge
